spring:
  application:
    name: backend

  datasource:
    url: jdbc:mysql://localhost:3306/Mini_Social_Media
    username: root
    password: Duyanh2004@
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: HikariCP
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

  security:
    user:
      name: admin
      password: 123456

  jpa:
    hibernate:
      ddl-auto: update

  data:
    mongodb:
      uri: mongodb://localhost:27017/room_renting
      database: room_renting
      auto-index-creation: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
server:
  address: 0.0.0.0
  port: 8081