spring:
  application:
    name: backend

  datasource:
    url: jdbc:mysql://localhost:3306/mini_social_media?useUnicode=true&characterEncoding=UTF-8&connectionCollation=utf8mb4_unicode_ci
    username: root
    password: Duyanh090@
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: HikariCP
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

  web:
    resources:
      static-locations:
        - "file:///C:/Social-Media-Backend/media/post_media/"
        - "file:///C:/Social-Media-Backend/media/message_media/"
        - "file:///C:/Social-Media-Backend/media/comment_media/"
      cache:
        period: 0

  jpa:
    hibernate:
      ddl-auto: update

  data:
    mongodb:
      uri: mongodb://localhost:27017/mini_social_media
      database: mini_social_media
      auto-index-creation: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
server:
  address: 0.0.0.0
  port: 8081